server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
<<<<<<< HEAD
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://vitalsync-backend:3000/;
        proxy_set_header Host $host;
=======
        try_files  / /index.html;
    }
    location /api/ {
        proxy_pass http://vitalsync-backend:3000/;
        proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
>>>>>>> 372958d (commit des dockerfiles)
    }
}
