version: '3.8'
services:
  vitalsync-db:
    image: postgres:15-alpine
    environment:
<<<<<<< HEAD
      POSTGRES_USER: ${DB_USER:-vitalsync}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-vitalsync_pass}
      POSTGRES_DB: ${DB_NAME:-vitalsync_db}
=======
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
>>>>>>> 372958d (commit des dockerfiles)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vitalsync-network
  vitalsync-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - vitalsync-db
    networks:
      - vitalsync-network
  vitalsync-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - vitalsync-backend
    networks:
      - vitalsync-network
networks:
  vitalsync-network:
    driver: bridge
volumes:
  postgres_data:
